{ pkgs, hgj_home, ... }:
let
  kittyDracula =
    with pkgs;
    stdenv.mkDerivation {
      name = "kitty-dracula-theme";
      src = fetchFromGitHub {
        owner = "dracula";
        repo = "kitty";
        rev = "6d6239a";
        sha256 = "1fyclzglw4jz0vrglwg6v644bhr7w7mb1d95lagy7iz14gybli0i";
      };
      installPhase = ''
        mkdir -p $out
        cp dracula.conf diff.conf $out/
      '';
    };

in
{
  xdg = {
    enable = true;

    configHome = "${hgj_home}/.config";
    dataHome = "${hgj_home}/.local/share";
    cacheHome = "${hgj_home}/.cache";
    configFile = {
      "fontconfig/fonts.conf".text = ''
        <?xml version='1.0'?>
        <!-- Generated by Hyunggyu Jang. -->
        <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
        <fontconfig>
          <dir>/Library/Fonts</dir>
          <dir>${hgj_home}/Library/Fonts</dir>
        </fontconfig>
      '';
      "pip/pip.conf".source = ./files/xdg/pip.conf;
      "afew/config".source = ./files/xdg/afew/config;

      "kitty/dracula.conf".source = "${kittyDracula}/dracula.conf";
      "kitty/diff.conf".source = "${kittyDracula}/diff.conf";
      "kitty/kitty.conf".source = ./files/xdg/kitty/kitty.conf;
      "helix/config.toml".source = ./files/xdg/helix/config.toml;
      "zathura/zathurarc".source = ./files/xdg/zathura/zathurarc;
      "karabiner/karabiner.json".source = ./files/xdg/karabiner/karabiner.json;
      "youtube-dl/config".source = ./files/xdg/youtube-dl/config;
      "zed/themes/Nano.json".source = ./files/xdg/zed/Nano.json;
      "zed/keymap.json".source = ./files/xdg/zed/keymap.json;
      "zed/settings.json".source = ./files/xdg/zed/settings.json;
    };
  };
}
