{ hgj_home, ... }:
{
  xdg = {
    enable = true;

    configHome = "${hgj_home}/.config";
    dataHome = "${hgj_home}/.local/share";
    cacheHome = "${hgj_home}/.cache";
    configFile = {
      "fontconfig/fonts.conf".text = ''
        <?xml version='1.0'?>
        <!-- Generated by Hyunggyu Jang. -->
        <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
        <fontconfig>
          <dir>/Library/Fonts</dir>
          <dir>${hgj_home}/Library/Fonts</dir>
        </fontconfig>
      '';
      "pip/pip.conf".source = ./files/xdg/pip.conf;
      "afew/config".source = ./files/xdg/afew/config;

      "kitty/dracula.conf".source = ./files/xdg/kitty/dracula.conf;
      "kitty/diff.conf".source = ./files/xdg/kitty/diff.conf;
      "kitty/diff-dark.conf".source = ./files/xdg/kitty/diff-dark.conf;
      "kitty/diff-light.conf".source = ./files/xdg/kitty/diff-light.conf;
      "kitty/alucard-light.conf".source = ./files/xdg/kitty/alucard-light.conf;
      "kitty/dark-theme.auto.conf".source = ./files/xdg/kitty/dark-theme.auto.conf;
      "kitty/light-theme.auto.conf".source = ./files/xdg/kitty/light-theme.auto.conf;
      "kitty/no-preference-theme.auto.conf".source = ./files/xdg/kitty/no-preference-theme.auto.conf;
      "kitty/kitty.conf".source = ./files/xdg/kitty/kitty.conf;
      "helix/config.toml".source = ./files/xdg/helix/config.toml;
      "zathura/zathurarc".source = ./files/xdg/zathura/zathurarc;
      "karabiner/karabiner.json".source = ./files/xdg/karabiner/karabiner.json;
      "youtube-dl/config".source = ./files/xdg/youtube-dl/config;
      "zed/themes/Nano.json".source = ./files/xdg/zed/Nano.json;
      "zed/keymap.json".source = ./files/xdg/zed/keymap.json;
      "zed/settings.json".source = ./files/xdg/zed/settings.json;
    };
  };
}
