{ pkgs, hgj_home, ... }:
let
  kittyDracula = with pkgs;
    stdenv.mkDerivation {
      name = "kitty-dracula-theme";
      src = fetchFromGitHub {
        owner = "dracula";
        repo = "kitty";
        rev = "6d6239a";
        sha256 = "1fyclzglw4jz0vrglwg6v644bhr7w7mb1d95lagy7iz14gybli0i";
      };
      installPhase = ''
        mkdir -p $out
        cp dracula.conf diff.conf $out/
      '';
    };

in
{
  xdg = {
    enable = true;

    configHome = "${hgj_home}/.config";
    dataHome = "${hgj_home}/.local/share";
    cacheHome = "${hgj_home}/.cache";
    configFile = {
      "fontconfig/fonts.conf".text = ''
        <?xml version='1.0'?>
        <!-- Generated by Hyunggyu Jang. -->
        <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
        <fontconfig>
          <dir>/Library/Fonts</dir>
          <dir>${hgj_home}/Library/Fonts</dir>
        </fontconfig>
      '';
      "pip/pip.conf".text = ''
        [global]
        break-system-packages = true
      '';
      "afew/config".text = ''
        [MailMover]
        folders = account.nagoya/Inbox account.nagoya/Trash
        rename = True

        account.nagoya/Inbox = 'tag:trash':'account.nagoya/Trash' 'NOT tag:inbox AND tag:lab':'account.nagoya/Lab' 'NOT tag:inbox AND tag:school':'account.nagoya/School' 'NOT tag:inbox AND NOT tag:trash':'account.nagoya/Archive'
        account.nagoya/Trash = 'NOT tag:trash':'account.nagoya/Inbox'

        [FolderNameFilter]
        folder_blacklist = account.nagoya account.gmail mail Archive
        folder_transforms = Drafts:draft Junk:spam
        folder_lowercases = true
        maildir_separator = /
      '';

      "kitty/dracula.conf".source = "${kittyDracula}/dracula.conf";
      "kitty/diff.conf".source = "${kittyDracula}/diff.conf";
      "kitty/kitty.conf".text = ''
        allow_remote_control yes

        hide_window_decorations yes

        font_family      Roboto Mono
        font_size        14.0

        macos_thicken_font 0.5

        macos_option_as_alt yes
        macos_hide_from_tasks no
        macos_quit_when_last_window_closed yes

        include dracula.conf
      '';
      "helix/config.toml".text = ''
        [editor.cursor-shape]
        insert = "bar"
        normal = "block"
        select = "underline"
      '';
      "zathura/zathurarc".text = "set selection-clipboard clipboard";
      "karabiner/karabiner.json".source = ../karabiner.json;
      "youtube-dl/config".text = ''
        # Save all vides under Youtube directory in cloud server
        -o ~/storage/Youtube/%(title)s.%(ext)s
      '';
      "zed/themes/Nano.json".source = ../Zed/Nano.json;
      "zed/keymap.json".source = ../Zed/keymap.json;
      "zed/settings.json".source = ../Zed/settings.json;
    };
  };
}
